config/routes.rb
Rails.application.routes.draw do
  resources :photos
  root to: 'photos#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, default_url: "/images/:style/missing.png", styles: { original: { height: "100%", width: "100%" } , medium:"300x300>", thumb:"100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    Photo.create(photo_params)
    redirect_to root_path
  end

  def photo_params
    params.require(:photo).permit(:title, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramPractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<% @photos.each do |photo| %>
  <%= photo.title %>
  <%= image_tag(photo.image.url :medium) %>
<% end %>

<%= link_to 'Add photo', new_photo_path %>

app/views/photos/new.html.erb
<%= form_for @photo do |p| %>
  <%= p.label :title %>
  <%= p.text_field :title %>
  <%= p.file_field :image %>
  <%= p.submit 'Upload photo' %>
<% end %>